#include "data.sqf"

_loadoutIndex = lbCurSel 1500;
_factionIndex = lbCurSel 1501;


//Add error handling
_faction = elp_factions select _factionIndex;
_loadout = _faction select _loadoutIndex;
player setUnitLoadout _loadout;


/*
switch (_factionIndex) do
{
	case 0: {
		switch (_loadoutIndex) do 
		{
			case 0: {player setUnitLoadout elp_raiders_rifleman_m4};
			case 1: {player setUnitLoadout [["rhs_weap_mk18_KAC_bk","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_su230",[],[],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_assaulter_belt_coy",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",6,30],["rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",4,30],["HandGrenade",3,1],["SmokeShell",3,1],["SmokeShellPurple",1,1]]],["tfa_bp_hydration_coy",[["ACE_SpraypaintGreen",1],["ACE_EntrenchingTool",1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
			case 2: {player setUnitLoadout [["CUP_arifle_Mk17_CQC_Black","rhsusf_acc_aac_762sdn6_silencer","CUP_acc_ANPEQ_15_Flashlight_Black_L","rhsusf_acc_su230",[],[],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_marksman_belt_coy",[["rhs_mag_20Rnd_SCAR_762x51_mk316_special_bk",8,20],["rhs_mag_20Rnd_SCAR_762x51_m62_tracer",4,20]]],["tfa_bp_hydration_coy",[["HandGrenade",3,1],["SmokeShell",3,1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
			case 3: {player setUnitLoadout [["rhs_weap_m4a1_blockII_M203_bk","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_su230",[],[],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_grenadier_belt_coy",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",6,30],["rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",4,30],["HandGrenade",3,1],["SmokeShell",3,1],["SmokeShellPurple",1,1],["rhs_mag_M433_HEDP",10,1],["1Rnd_SmokeRed_Grenade_shell",2,1]]],["tfa_bp_hydration_coy",[["ACE_SpraypaintGreen",1],["ACE_EntrenchingTool",1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
			case 4: {player setUnitLoadout [["rhs_weap_mk18_m320","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_su230",[],["rhs_mag_M433_HEDP",1],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_grenadier_belt_coy",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",6,30],["rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",4,30],["HandGrenade",3,1],["SmokeShell",3,1],["SmokeShellPurple",1,1],["rhs_mag_M433_HEDP",10,1],["1Rnd_SmokeRed_Grenade_shell",2,1]]],["tfa_bp_hydration_coy",[["ACE_SpraypaintGreen",1],["ACE_EntrenchingTool",1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
			case 5: {player setUnitLoadout [["rhs_weap_m249_pip_S","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Flashlight_Black_L","rhsusf_acc_su230",["rhsusf_200Rnd_556x45_soft_pouch",200],[],"rhsusf_acc_saw_bipod"],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_hgunner_coy",[["rhsusf_200Rnd_556x45_soft_pouch",3,200],["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",3,200]]],["tfa_bp_hydration_coy",[["ACE_EntrenchingTool",1],["SmokeShell",3,1],["HandGrenade",2,1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
			case 6: {player setUnitLoadout [["CUP_lmg_Mk48","muzzle_snds_H_MG_blk_F","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_su230",["150Rnd_762x51_Box",150],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_hgunner_coy",[["150Rnd_762x51_Box",3,150],["CUP_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M",3,100]]],["tfa_bp_hydration_coy",[["ACE_EntrenchingTool",1],["SmokeShell",3,1],["HandGrenade",2,1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
			case 7: {player setUnitLoadout [["rhs_weap_mk18_bk","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Flashlight_Black_L","rhsusf_acc_su230",[],[],"rhsusf_acc_grip2"],[],["rhsusf_weap_glock17g4","","","",[],[],""],["Gen3_M81",[["ACE_CableTie",4],["ACE_Flashlight_XL50",1],["ACE_MapTools",1]]],["tfa_v_mmac_medic_belt_coy",[["ACE_EntrenchingTool",1],["rhs_mag_30Rnd_556x45_Mk318_Stanag",9,30],["rhsusf_mag_17Rnd_9x19_FMJ",3,17],["SmokeShell",4,1]]],["B_Kitbag_cbr",[["ACE_adenosine",15],["ACE_fieldDressing",40],["ACE_bloodIV",8],["ACE_bloodIV_250",10],["ACE_bloodIV_500",10],["ACE_epinephrine",15],["ACE_morphine",15],["ACE_splint",15],["ACE_tourniquet",4]]],"CUP_H_OpsCore_Tan","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","ItemMicroDAGR","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
			case 8: {player setUnitLoadout [["rhs_weap_m4a1_blockII_M203_bk","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_su230",[],[],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_grenadier_belt_coy",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",6,30],["rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",4,30],["HandGrenade",3,1],["SmokeShell",3,1],["SmokeShellPurple",1,1],["rhs_mag_M433_HEDP",10,1],["1Rnd_SmokeRed_Grenade_shell",2,1]]],["tfa_bp_hydration_coy",[["ACE_SpraypaintGreen",1],["ACE_EntrenchingTool",1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
			case 9: {player setUnitLoadout [["rhs_weap_mk18_m320","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_su230",[],["rhs_mag_M433_HEDP",1],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_grenadier_belt_coy",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",6,30],["rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",4,30],["HandGrenade",3,1],["SmokeShell",3,1],["SmokeShellPurple",1,1],["rhs_mag_M433_HEDP",10,1],["1Rnd_SmokeRed_Grenade_shell",2,1]]],["tfa_bp_hydration_coy",[["ACE_SpraypaintGreen",1],["ACE_EntrenchingTool",1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
			case 10: {player setUnitLoadout [["CUP_arifle_Mk17_CQC_Black","rhsusf_acc_aac_762sdn6_silencer","CUP_acc_ANPEQ_15_Flashlight_Black_L","rhsusf_acc_su230",[],[],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_marksman_belt_coy",[["rhs_mag_20Rnd_SCAR_762x51_mk316_special_bk",8,20],["rhs_mag_20Rnd_SCAR_762x51_m62_tracer",4,20]]],["tfa_bp_hydration_coy",[["HandGrenade",3,1],["SmokeShell",3,1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
			case 11: {player setUnitLoadout [["rhs_weap_mk18_m320","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_su230",[],["1Rnd_SmokeRed_Grenade_shell",1],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_cpc_communicationsbelt_coy_patch",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",6,30],["rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",4,30],["rhs_mag_M433_HEDP",7,1],["UGL_FlareRed_F",6,1],["1Rnd_SmokeGreen_Grenade_shell",4,1]]],["tfw_ilbe_coy",[["ACE_SpraypaintGreen",1],["ACE_EntrenchingTool",1],["B_IR_Grenade",6,1],["Chemlight_blue",4,1],["Chemlight_green",4,1],["SmokeShellBlue",4,1],["SmokeShellGreen",4,1],["SmokeShellPurple",2,1],["SmokeShellRed",4,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_HandFlare_Green",2,1],["ACE_HandFlare_Red",2,1]]],"CUP_H_OpsCore_Black_SF","rhs_googles_clear",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemcTab","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
			case 12: {player setUnitLoadout [["CUP_srifle_M110_black","CUP_muzzle_snds_M110_black","CUP_acc_ANPEQ_15_Flashlight_Black_L","rhsusf_acc_LEUPOLDMK4_2_mrds",[],[],"rhsusf_acc_harris_bipod"],[],["rhsusf_weap_glock17g4","","","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_marksman_belt_coy",[["CUP_20Rnd_762x51_B_M110",6,20],["CUP_20Rnd_TE1_Red_Tracer_762x51_M110",4,20],["SmokeShell",3,1],["HandGrenade",3,1],["SmokeShellBlue",1,1],["SmokeShellPurple",1,1]]],["tfa_bp_hydration_coy",[["CUP_H_OpsCore_Spray_US_SF",1],["rhsusf_ANPVS_15",1],["ACE_RangeCard",1],["ACE_IR_Strobe_Item",2],["ACE_EntrenchingTool",1]]],"tfa_booniehat_m81","rhs_googles_clear",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter",""]]};
			case 13: {player setUnitLoadout [["rhs_weap_m4a1_blockII_KAC_bk","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_su230",[],[],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_assaulter_belt_coy",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",6,30],["rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",4,30],["HandGrenade",3,1],["SmokeShell",3,1],["SmokeShellPurple",1,1]]],["tfw_ilbe_coy",[["ACE_SpraypaintGreen",1],["ACE_EntrenchingTool",1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
			case 14: {player setUnitLoadout [["CUP_arifle_Mk17_CQC_Black","rhsusf_acc_aac_762sdn6_silencer","CUP_acc_ANPEQ_15_Flashlight_Black_L","rhsusf_acc_su230",[],[],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_marksman_belt_coy",[["rhs_mag_20Rnd_SCAR_762x51_mk316_special_bk",8,20],["rhs_mag_20Rnd_SCAR_762x51_m62_tracer",4,20]]],["tfw_ilbe_coy",[["HandGrenade",3,1],["SmokeShell",3,1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
			case 15: {player setUnitLoadout [["rhs_weap_m4a1_blockII_M203_bk","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_su230",[],[],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_grenadier_belt_coy",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",6,30],["rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",4,30],["HandGrenade",3,1],["SmokeShell",3,1],["SmokeShellPurple",1,1],["rhs_mag_M433_HEDP",10,1],["1Rnd_SmokeRed_Grenade_shell",2,1]]],["tfw_ilbe_coy",[["ACE_SpraypaintGreen",1],["ACE_EntrenchingTool",1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
			case 16: {player setUnitLoadout [["rhs_weap_mk18_m320","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_su230",[],["rhs_mag_M433_HEDP",1],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_grenadier_belt_coy",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",6,30],["rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",4,30],["HandGrenade",3,1],["SmokeShell",3,1],["SmokeShellPurple",1,1],["rhs_mag_M433_HEDP",10,1],["1Rnd_SmokeRed_Grenade_shell",2,1]]],["tfw_ilbe_coy",[["ACE_SpraypaintGreen",1],["ACE_EntrenchingTool",1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
			case 17: {player setUnitLoadout [["rhs_weap_m4_carryhandle","","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_Mk318_PMAG",30],[],""],[],["CUP_hgun_M9A1","","","",["CUP_15Rnd_9x19_M9",15],[],""],["rhs_uniform_FROG01_wd",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_splint",2],["ACE_tourniquet",2],["rhsusf_mag_15Rnd_9x19_FMJ",2,15]]],["CUP_V_B_Eagle_SPC_Crew",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",4,30],["SmokeShellBlue",2,1],["SmokeShellGreen",2,1],["SmokeShell",2,1]]],[],"rhsusf_cvc_green_helmet","rhs_ess_black",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
			case 18: {player setUnitLoadout [["rhs_weap_m4_carryhandle","","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_Mk318_PMAG",30],[],""],[],["CUP_hgun_M9A1","","","",["CUP_15Rnd_9x19_M9",15],[],""],["rhs_uniform_FROG01_d",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_splint",2],["ACE_tourniquet",2],["rhsusf_mag_15Rnd_9x19_FMJ",2,15]]],["CUP_V_B_Eagle_SPC_Crew",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",4,30],["SmokeShellBlue",2,1],["SmokeShellGreen",2,1],["SmokeShell",2,1]]],[],"rhsusf_cvc_helmet","rhs_ess_black",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
			case 19: {player setUnitLoadout [[],[],["CUP_hgun_M9A1","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["U_B_PilotCoveralls",[["ACE_packingBandage",8],["ACE_epinephrine",2],["ACE_morphine",2],["B_IR_Grenade",2,1],["Chemlight_blue",3,1],["rhsusf_mag_15Rnd_9x19_FMJ",2,15]]],[],[],"H_PilotHelmetFighter_B","",[],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter",""]]};
			case 20: {player setUnitLoadout [["rhs_weap_m4","","","rhsusf_acc_eotech_552",["rhs_mag_30Rnd_556x45_Mk318_PMAG",30],[],""],[],["CUP_hgun_M9A1","","","",["CUP_15Rnd_9x19_M9",15],[],""],["U_B_HeliPilotCoveralls",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",3],["Chemlight_blue",4,1]]],["CUP_V_B_PilotVest",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",3,30],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["SmokeShellGreen",2,1],["SmokeShellBlue",2,1],["SmokeShellPurple",2,1]]],[],"rhsusf_hgu56p_visor_mask_green_mo","",[],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
			default {hint "Loadout not Implemented"};
		};
	};
	default {hint "Faction not Implemented"};
};
*/


