//Roles for each faction
//marsocLoadouts = ["Rifleman (M4 Block II)", "Rifleman (MK 18 SBR)", "Heavy Rifleman (MK 17)", "Grenadier (M4 Block II + M203)", "Grenadier (MK 18 SBR + M320)", "Auto. Rifleman (M249)", "Hvy Auto. Rifleman (MK48)", "SARC (MK 18 SBR)", "El. Leader (M4 Block II + M203)", "El. Leader (MK 18 SBR + M320)", "El. Leader (MK 17)", "JTAC (MK 18 SBR + M320)", "Scout Sniper (M110)", "Team Leader (M4 Block II)", "T. Leader (MK 17)", "T. Leader (M4 Block II + M203)", "T. Leader (MK 18 SBR + M320)", "Crewman Woodland (M4)", "Crewman Desert (M4)", "Fixed Wing Pilot (M9 Berreta)", "Rotary Pilot (M4)"];
//pmcLoadouts = ["Contractor (M4)", "Contractor (MK 18)", "Pilot (MP5)"];

//Loudouts
////Raiders
elp_raiders_rifleman_m4 = [["rhs_weap_m4a1_blockII_KAC_bk","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_su230",[],[],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_assaulter_belt_coy",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",6,30],["rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",4,30],["HandGrenade",3,1],["SmokeShell",3,1],["SmokeShellPurple",1,1]]],["tfa_bp_hydration_coy",[["ACE_SpraypaintGreen",1],["ACE_EntrenchingTool",1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]];
elp_raiders_rifleman_mk18 = [["rhs_weap_mk18_KAC_bk","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_su230",[],[],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_assaulter_belt_coy",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",6,30],["rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",4,30],["HandGrenade",3,1],["SmokeShell",3,1],["SmokeShellPurple",1,1]]],["tfa_bp_hydration_coy",[["ACE_SpraypaintGreen",1],["ACE_EntrenchingTool",1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]];
elp_raiders_heavyrifleman_mk17 = [["CUP_arifle_Mk17_CQC_Black","rhsusf_acc_aac_762sdn6_silencer","CUP_acc_ANPEQ_15_Flashlight_Black_L","rhsusf_acc_su230",[],[],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_marksman_belt_coy",[["rhs_mag_20Rnd_SCAR_762x51_mk316_special_bk",8,20],["rhs_mag_20Rnd_SCAR_762x51_m62_tracer",4,20]]],["tfa_bp_hydration_coy",[["HandGrenade",3,1],["SmokeShell",3,1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]];
elp_raiders_grenadier_m203 = [["rhs_weap_m4a1_blockII_M203_bk","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_su230",[],[],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_grenadier_belt_coy",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",6,30],["rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",4,30],["HandGrenade",3,1],["SmokeShell",3,1],["SmokeShellPurple",1,1],["rhs_mag_M433_HEDP",10,1],["1Rnd_SmokeRed_Grenade_shell",2,1]]],["tfa_bp_hydration_coy",[["ACE_SpraypaintGreen",1],["ACE_EntrenchingTool",1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]];
elp_raiders_grenadire_m320 =[["rhs_weap_mk18_m320","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_su230",[],["rhs_mag_M433_HEDP",1],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_grenadier_belt_coy",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",6,30],["rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",4,30],["HandGrenade",3,1],["SmokeShell",3,1],["SmokeShellPurple",1,1],["rhs_mag_M433_HEDP",10,1],["1Rnd_SmokeRed_Grenade_shell",2,1]]],["tfa_bp_hydration_coy",[["ACE_SpraypaintGreen",1],["ACE_EntrenchingTool",1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]];
elp_raiders_autorifleman_m249 =[["rhs_weap_m249_pip_S","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Flashlight_Black_L","rhsusf_acc_su230",["rhsusf_200Rnd_556x45_soft_pouch",200],[],"rhsusf_acc_saw_bipod"],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_hgunner_coy",[["rhsusf_200Rnd_556x45_soft_pouch",3,200],["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",3,200]]],["tfa_bp_hydration_coy",[["ACE_EntrenchingTool",1],["SmokeShell",3,1],["HandGrenade",2,1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]];
elp_raiders_heavyautorifleman_mk48 = [["CUP_lmg_Mk48","muzzle_snds_H_MG_blk_F","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_su230",["150Rnd_762x51_Box",150],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_hgunner_coy",[["150Rnd_762x51_Box",3,150],["CUP_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M",3,100]]],["tfa_bp_hydration_coy",[["ACE_EntrenchingTool",1],["SmokeShell",3,1],["HandGrenade",2,1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]];
elp_raiders_sarc = [["rhs_weap_mk18_bk","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Flashlight_Black_L","rhsusf_acc_su230",[],[],"rhsusf_acc_grip2"],[],["rhsusf_weap_glock17g4","","","",[],[],""],["Gen3_M81",[["ACE_CableTie",4],["ACE_Flashlight_XL50",1],["ACE_MapTools",1]]],["tfa_v_mmac_medic_belt_coy",[["ACE_EntrenchingTool",1],["rhs_mag_30Rnd_556x45_Mk318_Stanag",9,30],["rhsusf_mag_17Rnd_9x19_FMJ",3,17],["SmokeShell",4,1]]],["B_Kitbag_cbr",[["ACE_adenosine",15],["ACE_fieldDressing",40],["ACE_bloodIV",8],["ACE_bloodIV_250",10],["ACE_bloodIV_500",10],["ACE_epinephrine",15],["ACE_morphine",15],["ACE_splint",15],["ACE_tourniquet",4]]],"CUP_H_OpsCore_Tan","rhs_googles_clear",["Binocular","","","",[],[],""],["ItemMap","ItemMicroDAGR","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]];
elp_raiders_elementlead_m203 = [["rhs_weap_m4a1_blockII_M203_bk","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_su230",[],[],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_grenadier_belt_coy",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",6,30],["rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",4,30],["HandGrenade",3,1],["SmokeShell",3,1],["SmokeShellPurple",1,1],["rhs_mag_M433_HEDP",10,1],["1Rnd_SmokeRed_Grenade_shell",2,1]]],["tfa_bp_hydration_coy",[["ACE_SpraypaintGreen",1],["ACE_EntrenchingTool",1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]];
elp_raiders_elementlead_m320 = [["rhs_weap_mk18_m320","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_su230",[],["rhs_mag_M433_HEDP",1],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_grenadier_belt_coy",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",6,30],["rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",4,30],["HandGrenade",3,1],["SmokeShell",3,1],["SmokeShellPurple",1,1],["rhs_mag_M433_HEDP",10,1],["1Rnd_SmokeRed_Grenade_shell",2,1]]],["tfa_bp_hydration_coy",[["ACE_SpraypaintGreen",1],["ACE_EntrenchingTool",1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]];
elp_raiders_elementlead_mk17 = [["CUP_arifle_Mk17_CQC_Black","rhsusf_acc_aac_762sdn6_silencer","CUP_acc_ANPEQ_15_Flashlight_Black_L","rhsusf_acc_su230",[],[],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_marksman_belt_coy",[["rhs_mag_20Rnd_SCAR_762x51_mk316_special_bk",8,20],["rhs_mag_20Rnd_SCAR_762x51_m62_tracer",4,20]]],["tfa_bp_hydration_coy",[["HandGrenade",3,1],["SmokeShell",3,1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]];
elp_raiders_jtac = [["rhs_weap_mk18_m320","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_su230",[],["1Rnd_SmokeRed_Grenade_shell",1],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_cpc_communicationsbelt_coy_patch",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",6,30],["rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",4,30],["rhs_mag_M433_HEDP",7,1],["UGL_FlareRed_F",6,1],["1Rnd_SmokeGreen_Grenade_shell",4,1]]],["tfw_ilbe_coy",[["ACE_SpraypaintGreen",1],["ACE_EntrenchingTool",1],["B_IR_Grenade",6,1],["Chemlight_blue",4,1],["Chemlight_green",4,1],["SmokeShellBlue",4,1],["SmokeShellGreen",4,1],["SmokeShellPurple",2,1],["SmokeShellRed",4,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_HandFlare_Green",2,1],["ACE_HandFlare_Red",2,1]]],"CUP_H_OpsCore_Black_SF","rhs_googles_clear",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemcTab","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]];
elp_raiders_scoutsniper = [["CUP_srifle_M110_black","CUP_muzzle_snds_M110_black","CUP_acc_ANPEQ_15_Flashlight_Black_L","rhsusf_acc_LEUPOLDMK4_2_mrds",[],[],"rhsusf_acc_harris_bipod"],[],["rhsusf_weap_glock17g4","","","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_marksman_belt_coy",[["CUP_20Rnd_762x51_B_M110",6,20],["CUP_20Rnd_TE1_Red_Tracer_762x51_M110",4,20],["SmokeShell",3,1],["HandGrenade",3,1],["SmokeShellBlue",1,1],["SmokeShellPurple",1,1]]],["tfa_bp_hydration_coy",[["CUP_H_OpsCore_Spray_US_SF",1],["rhsusf_ANPVS_15",1],["ACE_RangeCard",1],["ACE_IR_Strobe_Item",2],["ACE_EntrenchingTool",1]]],"tfa_booniehat_m81","rhs_googles_clear",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter",""]];
elp_raiders_teamleader_m4 = [["rhs_weap_m4a1_blockII_KAC_bk","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_su230",[],[],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_assaulter_belt_coy",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",6,30],["rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",4,30],["HandGrenade",3,1],["SmokeShell",3,1],["SmokeShellPurple",1,1]]],["tfw_ilbe_coy",[["ACE_SpraypaintGreen",1],["ACE_EntrenchingTool",1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]];
elp_raiders_teamleader_mk17 = [["CUP_arifle_Mk17_CQC_Black","rhsusf_acc_aac_762sdn6_silencer","CUP_acc_ANPEQ_15_Flashlight_Black_L","rhsusf_acc_su230",[],[],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_marksman_belt_coy",[["rhs_mag_20Rnd_SCAR_762x51_mk316_special_bk",8,20],["rhs_mag_20Rnd_SCAR_762x51_m62_tracer",4,20]]],["tfw_ilbe_coy",[["HandGrenade",3,1],["SmokeShell",3,1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]];
elp_raiders_teamleader_m203 = [["rhs_weap_m4a1_blockII_M203_bk","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_su230",[],[],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_grenadier_belt_coy",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",6,30],["rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",4,30],["HandGrenade",3,1],["SmokeShell",3,1],["SmokeShellPurple",1,1],["rhs_mag_M433_HEDP",10,1],["1Rnd_SmokeRed_Grenade_shell",2,1]]],["tfw_ilbe_coy",[["ACE_SpraypaintGreen",1],["ACE_EntrenchingTool",1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]];
elp_raiders_teamleader_m320 = [["rhs_weap_mk18_m320","rhsusf_acc_nt4_black","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_su230",[],["rhs_mag_M433_HEDP",1],""],[],["rhsusf_weap_glock17g4","","CUP_acc_CZ_M3X","",[],[],""],["CUP_U_CRYE_G3C_M81_US_V2",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",2],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["tfa_v_mmac_grenadier_belt_coy",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",6,30],["rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",4,30],["HandGrenade",3,1],["SmokeShell",3,1],["SmokeShellPurple",1,1],["rhs_mag_M433_HEDP",10,1],["1Rnd_SmokeRed_Grenade_shell",2,1]]],["tfw_ilbe_coy",[["ACE_SpraypaintGreen",1],["ACE_EntrenchingTool",1]]],"CUP_H_OpsCore_Spray_US_SF","rhs_googles_clear",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]];
elp_raiders_crewman_woodland =[["rhs_weap_m4_carryhandle","","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_Mk318_PMAG",30],[],""],[],["CUP_hgun_M9A1","","","",["CUP_15Rnd_9x19_M9",15],[],""],["rhs_uniform_FROG01_wd",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_splint",2],["ACE_tourniquet",2],["rhsusf_mag_15Rnd_9x19_FMJ",2,15]]],["CUP_V_B_Eagle_SPC_Crew",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",4,30],["SmokeShellBlue",2,1],["SmokeShellGreen",2,1],["SmokeShell",2,1]]],[],"rhsusf_cvc_green_helmet","rhs_ess_black",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]];
elp_raiders_crewman_desert = [["rhs_weap_m4_carryhandle","","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_Mk318_PMAG",30],[],""],[],["CUP_hgun_M9A1","","","",["CUP_15Rnd_9x19_M9",15],[],""],["rhs_uniform_FROG01_d",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_splint",2],["ACE_tourniquet",2],["rhsusf_mag_15Rnd_9x19_FMJ",2,15]]],["CUP_V_B_Eagle_SPC_Crew",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",4,30],["SmokeShellBlue",2,1],["SmokeShellGreen",2,1],["SmokeShell",2,1]]],[],"rhsusf_cvc_helmet","rhs_ess_black",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]];
elp_raiders_fixedwingpilot = [[],[],["CUP_hgun_M9A1","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["U_B_PilotCoveralls",[["ACE_packingBandage",8],["ACE_epinephrine",2],["ACE_morphine",2],["B_IR_Grenade",2,1],["Chemlight_blue",3,1],["rhsusf_mag_15Rnd_9x19_FMJ",2,15]]],[],[],"H_PilotHelmetFighter_B","",[],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter",""]];
elp_raiders_rotarypilot = [["rhs_weap_m4","","","rhsusf_acc_eotech_552",["rhs_mag_30Rnd_556x45_Mk318_PMAG",30],[],""],[],["CUP_hgun_M9A1","","","",["CUP_15Rnd_9x19_M9",15],[],""],["U_B_HeliPilotCoveralls",[["ACE_packingBandage",10],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_tourniquet",2],["ACE_splint",3],["Chemlight_blue",4,1]]],["CUP_V_B_PilotVest",[["rhs_mag_30Rnd_556x45_Mk318_PMAG",3,30],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["SmokeShellGreen",2,1],["SmokeShellBlue",2,1],["SmokeShellPurple",2,1]]],[],"rhsusf_hgu56p_visor_mask_green_mo","",[],["ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]];


elp_raiders = [
	["Rifleman (M4 Block II)", elp_raiders_rifleman_m4], 
	["Rifleman (MK 18 SBR)", elp_raiders_rifleman_mk18],
	["Heavy Rifleman (MK 17)", elp_raiders_heavyrifleman_mk17],
	["Grenadier (M4 Block II + M203)", elp_raiders_grenadier_m203],
	["Grenadier (MK 18 SBR + M320)", elp_raiders_grenadire_m320],
	["Auto. Rifleman (M249)", elp_raiders_autorifleman_m249],
	["Hvy Auto. Rifleman (MK48)", elp_raiders_heavyautorifleman_mk48],
	["SARC (MK 18 SBR)", elp_raiders_sarc],
	["El. Leader (M4 Block II + M203)", elp_raiders_elementlead_m203],
	["El. Leader (MK 18 SBR + M320)", elp_raiders_elementlead_m320],
	["El. Leader (MK 17)", elp_raiders_elementlead_mk17],
	["JTAC (MK 18 SBR + M320)", elp_raiders_jtac],
	["Scout Sniper (M110)", elp_raiders_scoutsniper],
	["Team Leader (M4 Block II)", elp_raiders_teamleader_m4],
	["T. Leader (MK 17)", elp_raiders_teamleader_mk17],
	["T. Leader (M4 Block II + M203)", elp_raiders_teamleader_m203],
	["T. Leader (MK 18 SBR + M320)", elp_raiders_teamleader_m320],
	["Crewman Woodland (M4)", elp_raiders_crewman_woodland],
	["Crewman Desert (M4)", elp_raiders_crewman_desert],
	["Fixed Wing Pilot (M9 Berreta)", elp_raiders_fixedwingpilot],
	["Rotary Pilot (M4)", elp_raiders_rotarypilot]
];

////USMC
elp_usmc_rifleman = [["CUP_arifle_M16A2","","CUP_acc_ANPEQ_2_grey","",["rhs_mag_30Rnd_556x45_Mk318_Stanag",30],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["CUP_U_B_BDUv2_roll2_DCU",[["ACE_packingBandage",10],["ACE_adenosine",2],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_splint",1],["ACE_EntrenchingTool",1],["ACE_bodyBag",1],["ACE_CableTie",1],["ACE_Fortify",1]]],["CUP_V_B_Interceptor_Rifleman_M81",[["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_Mk318_Stanag",8,30],["rhs_mag_m67",1,1],["SmokeShell",1,1]]],["tfa_eagle_m81",[["ACE_bloodIV",1],["ACE_DefusalKit",1],["ACE_MapTools",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["ACE_Flashlight_MX991",1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShellRed",2,1],["SmokeShellPurple",1,1],["SmokeShellGreen",1,1],["CUP_HandGrenade_M67",2,1],["rhs_mag_m713_Red",1,1],["rhs_mag_m715_Green",1,1],["rhs_mag_m714_White",2,1],["ACE_40mm_Flare_green",1,1],["ACE_40mm_Flare_red",1,1],["rhsusf_100Rnd_556x45_M855_soft_pouch_coyote",1,100]]],"rhsgref_helmet_pasgt_3color_desert_rhino","",["rhsusf_bino_m24_ARD","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152_9","ItemCompass","ItemWatch","CUP_NVG_PVS14"]];
elp_usmc_antitank = [["CUP_arifle_M16A2","","CUP_acc_ANPEQ_2_grey","",["rhs_mag_30Rnd_556x45_Mk318_Stanag",30],[],""],["rhs_weap_smaw_green","","","rhs_weap_optic_smaw",["rhs_mag_smaw_HEDP",1],[],""],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["CUP_U_B_BDUv2_roll2_DCU",[["ACE_packingBandage",10],["ACE_adenosine",2],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_splint",1],["ACE_EntrenchingTool",1],["ACE_bodyBag",1],["ACE_CableTie",1],["ACE_Fortify",1]]],["CUP_V_B_Interceptor_Rifleman_M81",[["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_Mk318_Stanag",8,30],["rhs_mag_m67",1,1],["SmokeShell",1,1]]],["tfa_eagle_m81",[["ACE_bloodIV",1],["ACE_DefusalKit",1],["ACE_MapTools",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["ACE_Flashlight_MX991",1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShellRed",2,1],["SmokeShellPurple",1,1],["SmokeShellGreen",1,1],["CUP_HandGrenade_M67",2,1],["rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",1,100],["rhs_mag_smaw_HEDP",2,1]]],"rhsgref_helmet_pasgt_3color_desert_rhino","",["rhsusf_bino_m24_ARD","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152_10","ItemCompass","ItemWatch","CUP_NVG_PVS14"]];
elp_usmc_basecommand = [[],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["CUP_U_B_BDUv2_roll2_DCU",[["ACE_packingBandage",10],["ACE_adenosine",2],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_splint",1],["ACE_EntrenchingTool",1],["ACE_bodyBag",1],["ACE_CableTie",1],["ACE_Fortify",1]]],["CUP_V_B_Interceptor_Rifleman_M81",[["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_Mk318_Stanag",8,30],["rhs_mag_m67",1,1],["SmokeShell",1,1]]],["tf_anprc155_coyote",[["ACE_bloodIV",1],["ACE_DefusalKit",1],["ACE_MapTools",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["ACE_Flashlight_MX991",1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShellRed",2,1],["SmokeShellPurple",1,1],["SmokeShellGreen",1,1],["CUP_HandGrenade_M67",2,1],["rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",1,100]]],"rhsgref_helmet_pasgt_3color_desert","",["rhsusf_bino_m24_ARD","","","",[],[],""],["ItemMap","ItemAndroid","tf_anprc152_13","ItemCompass","ItemWatch",""]];
epl_usmc_basecommand_noradio = [[],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["CUP_U_B_BDUv2_roll2_DCU",[["ACE_packingBandage",10],["ACE_adenosine",2],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_splint",1],["ACE_EntrenchingTool",1],["ACE_bodyBag",1],["ACE_CableTie",1],["ACE_Fortify",1]]],["CUP_V_B_Interceptor_Rifleman_M81",[["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_Mk318_Stanag",8,30],["rhs_mag_m67",1,1],["SmokeShell",1,1]]],[],"rhsgref_helmet_pasgt_3color_desert","",["rhsusf_bino_m24_ARD","","","",[],[],""],["ItemMap","ItemAndroid","tf_anprc152_15","ItemCompass","ItemWatch",""]];
epl_usmc_teamleader = [["CUP_arifle_M16A2","","CUP_acc_ANPEQ_2_Flashlight_Black_L","",["rhs_mag_30Rnd_556x45_Mk318_Stanag",30],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["CUP_U_B_BDUv2_roll2_DCU",[["ACE_packingBandage",10],["ACE_adenosine",2],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_splint",1],["ACE_EntrenchingTool",1],["ACE_bodyBag",1],["ACE_CableTie",1],["ACE_Fortify",1]]],["CUP_V_B_Interceptor_Rifleman_M81",[["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_Mk318_Stanag",8,30],["rhs_mag_m67",1,1],["SmokeShell",1,1]]],["tf_anprc155_coyote",[["ACE_bloodIV",1],["ACE_DefusalKit",1],["ACE_MapTools",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["ACE_Flashlight_MX991",1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShellRed",2,1],["SmokeShellPurple",1,1],["SmokeShellGreen",1,1],["CUP_HandGrenade_M67",2,1],["rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",1,100]]],"rhsgref_helmet_pasgt_3color_desert_rhino","",["rhsusf_bino_m24_ARD","","","",[],[],""],["ItemMap","ItemcTab","tf_anprc152_14","ItemCompass","ItemWatch","CUP_NVG_PVS14"]];
epl_usmc_spotter = [["CUP_arifle_M16A2","","CUP_acc_ANPEQ_2_grey","",["rhs_mag_30Rnd_556x45_Mk318_Stanag",30],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["CUP_U_B_BDUv2_roll2_DCU",[["ACE_packingBandage",10],["ACE_adenosine",2],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_splint",1],["ACE_EntrenchingTool",1],["ACE_bodyBag",1],["ACE_CableTie",1],["ACE_Fortify",1]]],["CUP_V_B_Interceptor_Rifleman_M81",[["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_Mk318_Stanag",8,30],["rhs_mag_m67",1,1],["SmokeShell",1,1]]],["tfa_eagle_m81",[["ACE_bloodIV",1],["ACE_DefusalKit",1],["ACE_MapTools",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_SpottingScope",1],["ACE_Tripod",1],["ACE_Flashlight_MX991",1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShellRed",2,1],["SmokeShellPurple",1,1],["SmokeShellGreen",1,1],["CUP_HandGrenade_M67",2,1],["rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",1,100]]],"rhsgref_helmet_pasgt_3color_desert_rhino","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152_16","ItemCompass","ItemWatch","CUP_NVG_PVS14"]];
epl_usmc_sniper = [["rhs_weap_m40a5_d","","","rhsusf_acc_M8541_low_d",["rhsusf_10Rnd_762x51_m993_Mag",10],[],"rhsusf_acc_harris_swivel"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["CUP_U_B_BDUv2_roll2_DCU",[["ACE_packingBandage",10],["ACE_adenosine",2],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_splint",1],["ACE_EntrenchingTool",1],["ACE_bodyBag",1],["ACE_CableTie",1],["ACE_Fortify",1]]],["CUP_V_B_Interceptor_Rifleman_M81",[["rhsusf_mag_15Rnd_9x19_FMJ",4,15],["rhs_mag_m67",1,1],["SmokeShell",1,1],["rhsusf_10Rnd_762x51_m993_Mag",4,10],["rhsusf_10Rnd_762x51_m118_special_Mag",4,10]]],["tfa_eagle_m81",[["ACE_bloodIV",1],["ACE_DefusalKit",1],["ACE_MapTools",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_Flashlight_MX991",1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShellRed",2,1],["SmokeShellPurple",1,1],["SmokeShellGreen",1,1],["CUP_HandGrenade_M67",2,1],["rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",1,100]]],"rhsgref_helmet_pasgt_3color_desert_rhino","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152_17","ItemCompass","ItemWatch","CUP_NVG_PVS14"]];
epl_usmc_sarc = [["CUP_arifle_M16A2","","CUP_acc_ANPEQ_2_grey","",["rhs_mag_30Rnd_556x45_Mk318_Stanag",30],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["CUP_U_B_BDUv2_roll2_DCU",[["ACE_packingBandage",10],["ACE_adenosine",2],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_splint",1],["ACE_EntrenchingTool",1],["ACE_bodyBag",1],["ACE_CableTie",1],["ACE_Fortify",1]]],["CUP_V_B_Interceptor_Rifleman_M81",[["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_Mk318_Stanag",8,30],["rhs_mag_m67",1,1],["SmokeShell",1,1]]],["tfa_eagle_m81",[["ACE_bloodIV",6],["ACE_DefusalKit",1],["ACE_MapTools",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["ACE_packingBandage",40],["ACE_plasmaIV",6],["ACE_salineIV",6],["ACE_surgicalKit",1],["ACE_tourniquet",10],["ACE_splint",10],["ACE_morphine",10],["ACE_epinephrine",10],["ACE_adenosine",10],["ACE_Flashlight_MX991",1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShellRed",2,1],["SmokeShellPurple",1,1],["SmokeShellGreen",1,1],["CUP_HandGrenade_M67",2,1],["rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",1,100]]],"rhsgref_helmet_pasgt_3color_desert_rhino","",["rhsusf_bino_m24_ARD","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch","CUP_NVG_PVS14"]];
epl_usmc_radiooperator = [["CUP_arifle_M16A2","","CUP_acc_ANPEQ_2_grey","",["rhs_mag_30Rnd_556x45_Mk318_Stanag",30],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["CUP_U_B_BDUv2_roll2_DCU",[["ACE_packingBandage",10],["ACE_adenosine",2],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_splint",1],["ACE_EntrenchingTool",1],["ACE_bodyBag",1],["ACE_CableTie",1],["ACE_Fortify",1]]],["CUP_V_B_Interceptor_Rifleman_M81",[["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_Mk318_Stanag",8,30],["rhs_mag_m67",1,1],["SmokeShell",1,1]]],["tf_anprc155_coyote",[["ACE_bloodIV",1],["ACE_DefusalKit",1],["ACE_MapTools",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["ACE_Flashlight_MX991",1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShellRed",2,1],["SmokeShellPurple",1,1],["SmokeShellGreen",1,1],["CUP_HandGrenade_M67",2,1],["rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",1,100]]],"rhsgref_helmet_pasgt_3color_desert_rhino","",["rhsusf_bino_m24_ARD","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch","CUP_NVG_PVS14"]];
epl_usmc_mmg = [["rhs_weap_m240B","","","",["Tier1_250Rnd_762x51_Belt_M62_Tracer",250],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["CUP_U_B_BDUv2_roll2_DCU",[["ACE_packingBandage",10],["ACE_adenosine",2],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_splint",1],["ACE_EntrenchingTool",1],["ACE_bodyBag",1],["ACE_CableTie",1],["ACE_Fortify",1]]],["CUP_V_B_Interceptor_Rifleman_M81",[["rhs_mag_m67",1,1],["SmokeShell",1,1],["Tier1_250Rnd_762x51_Belt_M62_Tracer",1,250]]],["tfa_eagle_m81",[["ACE_bloodIV",1],["ACE_DefusalKit",1],["ACE_MapTools",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["ACE_Flashlight_MX991",1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShellRed",2,1],["SmokeShellPurple",1,1],["SmokeShellGreen",1,1],["CUP_HandGrenade_M67",2,1],["Tier1_250Rnd_762x51_Belt_M993_AP",2,250],["Tier1_250Rnd_762x51_Belt_M62_Tracer",2,250]]],"rhsgref_helmet_pasgt_3color_desert_rhino","",["rhsusf_bino_m24_ARD","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152_20","ItemCompass","ItemWatch","CUP_NVG_PVS14"]];
epl_usmc_marksman = [["rhs_weap_m14_rail_wd","","","rhsusf_acc_M8541_low_d",["rhsusf_20Rnd_762x51_m993_Mag",20],[],"rhsusf_acc_harris_swivel"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["CUP_U_B_BDUv2_roll2_DCU",[["ACE_packingBandage",10],["ACE_adenosine",2],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_splint",1],["ACE_EntrenchingTool",1],["ACE_bodyBag",1],["ACE_CableTie",1],["ACE_Fortify",1]]],["CUP_V_B_Interceptor_Rifleman_M81",[["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_m67",1,1],["SmokeShell",1,1],["rhsusf_20Rnd_762x51_m993_Mag",4,20]]],["tfa_eagle_m81",[["ACE_bloodIV",1],["ACE_DefusalKit",1],["ACE_MapTools",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_Flashlight_MX991",1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShellRed",2,1],["SmokeShellPurple",1,1],["SmokeShellGreen",1,1],["CUP_HandGrenade_M67",2,1],["rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",1,100]]],"rhsgref_helmet_pasgt_3color_desert_rhino","",["rhsusf_bino_m24_ARD","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152_21","ItemCompass","ItemWatch","CUP_NVG_PVS14"]];
epl_usmc_lmg = [["rhs_weap_m249_pip","","","",["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",200],[],"rhsusf_acc_saw_bipod"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["CUP_U_B_BDUv2_roll2_DCU",[["ACE_packingBandage",10],["ACE_adenosine",2],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_splint",1],["ACE_EntrenchingTool",1],["ACE_bodyBag",1],["ACE_CableTie",1],["ACE_Fortify",1]]],["CUP_V_B_Interceptor_Rifleman_M81",[["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_m67",1,1],["SmokeShell",1,1],["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",1,200],["rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",1,100]]],["tfa_eagle_m81",[["ACE_bloodIV",1],["ACE_DefusalKit",1],["ACE_MapTools",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["ACE_Flashlight_MX991",1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShellRed",2,1],["SmokeShellPurple",1,1],["SmokeShellGreen",1,1],["CUP_HandGrenade_M67",2,1],["rhsusf_100Rnd_556x45_M995_soft_pouch_coyote",2,100],["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",1,200]]],"rhsgref_helmet_pasgt_3color_desert_rhino","",["rhsusf_bino_m24_ARD","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152_22","ItemCompass","ItemWatch","CUP_NVG_PVS14"]];
epl_usmc_jtac = [["CUP_arifle_M16A2","","CUP_acc_ANPEQ_2_grey","",["rhs_mag_30Rnd_556x45_Mk318_Stanag",30],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["CUP_U_B_BDUv2_roll2_DCU",[["ACE_packingBandage",10],["ACE_adenosine",2],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_splint",1],["ACE_EntrenchingTool",1],["ACE_bodyBag",1],["ACE_CableTie",1],["ACE_Fortify",1]]],["CUP_V_B_Interceptor_Rifleman_M81",[["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_Mk318_Stanag",8,30],["rhs_mag_m67",1,1],["SmokeShell",1,1]]],["tf_anprc155_coyote",[["ACE_bloodIV",1],["ACE_DefusalKit",1],["ACE_MapTools",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["ACE_Flashlight_MX991",1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShellRed",2,1],["SmokeShellPurple",2,1],["SmokeShellGreen",2,1],["CUP_HandGrenade_M67",2,1],["rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",1,100],["B_IR_Grenade",2,1],["SmokeShellOrange",2,1],["SmokeShellBlue",2,1],["SmokeShell",1,1]]],"rhsgref_helmet_pasgt_3color_desert_rhino","",["CUP_LRTV","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","tf_anprc152_23","ItemCompass","ItemWatch","CUP_NVG_PVS14"]];
epl_usmc_grenadier = [["CUP_arifle_M16A2_GL","","","",["rhs_mag_30Rnd_556x45_Mk318_Stanag",30],["rhs_mag_M433_HEDP",1],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["CUP_U_B_BDUv2_roll2_DCU",[["ACE_packingBandage",10],["ACE_adenosine",2],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_splint",1],["ACE_EntrenchingTool",1],["ACE_bodyBag",1],["ACE_CableTie",1],["ACE_Fortify",1]]],["CUP_V_B_Interceptor_Grenadier_M81",[["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_Mk318_Stanag",8,30],["rhs_mag_m67",1,1],["SmokeShell",1,1],["rhs_mag_M433_HEDP",7,1],["ACE_40mm_Flare_white",1,1]]],["tfa_eagle_m81",[["ACE_bloodIV",1],["ACE_DefusalKit",1],["ACE_MapTools",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["ACE_Flashlight_MX991",1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShellRed",2,1],["SmokeShellPurple",1,1],["SmokeShellGreen",1,1],["CUP_HandGrenade_M67",2,1],["rhs_mag_M433_HEDP",8,1],["rhs_mag_m713_Red",1,1],["rhs_mag_m715_Green",1,1],["rhs_mag_m714_White",2,1],["ACE_40mm_Flare_green",1,1],["ACE_40mm_Flare_red",1,1],["rhsusf_100Rnd_556x45_M855_soft_pouch_coyote",1,100]]],"rhsgref_helmet_pasgt_3color_desert_rhino","",["rhsusf_bino_m24_ARD","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ItemWatch","CUP_NVG_PVS14"]];
epl_usmc_eod = [["CUP_arifle_M16A2","","CUP_acc_ANPEQ_2_grey","",["rhs_mag_30Rnd_556x45_Mk318_Stanag",30],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["CUP_U_B_BDUv2_roll2_DCU",[["ACE_packingBandage",10],["ACE_adenosine",2],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_splint",1],["ACE_EntrenchingTool",1],["ACE_bodyBag",1],["ACE_CableTie",1],["ACE_Fortify",1]]],["CUP_V_B_Interceptor_Rifleman_M81",[["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_Mk318_Stanag",8,30],["rhs_mag_m67",1,1],["SmokeShell",1,1]]],["tfa_eagle_m81",[["ACE_DefusalKit",1],["ACE_MapTools",1],["ACE_SpraypaintGreen",2],["ACE_SpraypaintRed",2],["ACE_M26_Clacker",1],["ACE_Clacker",1],["ACE_SpraypaintBlue",2],["ACE_bloodIV_500",1],["ACE_Flashlight_MX991",1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShellRed",2,1],["SmokeShellPurple",1,1],["SmokeShellGreen",1,1],["CUP_HandGrenade_M67",2,1],["rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",1,100],["DemoCharge_Remote_Mag",4,1],["SatchelCharge_Remote_Mag",2,1]]],"rhsgref_helmet_pasgt_3color_desert_rhino","",["rhsusf_bino_m24_ARD","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152_25","ItemCompass","ItemWatch","CUP_NVG_PVS14"]];
epl_usmc_elementlead = [["CUP_arifle_M16A2","","CUP_acc_ANPEQ_2_Flashlight_Black_L","rhsusf_acc_ACOG3_USMC",["rhs_mag_30Rnd_556x45_Mk318_Stanag",30],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_JHP",15],[],""],["CUP_U_B_BDUv2_roll2_DCU",[["ACE_packingBandage",10],["ACE_adenosine",2],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_splint",1],["ACE_EntrenchingTool",1],["ACE_bodyBag",1],["ACE_CableTie",1],["ACE_Fortify",1]]],["CUP_V_B_Interceptor_Rifleman_M81",[["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_Mk318_Stanag",8,30],["rhs_mag_m67",1,1],["SmokeShell",1,1]]],["tfa_eagle_m81",[["ACE_bloodIV",1],["ACE_DefusalKit",1],["ACE_MapTools",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["ACE_Flashlight_MX991",1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShellRed",2,1],["SmokeShellPurple",1,1],["SmokeShellGreen",1,1],["CUP_HandGrenade_M67",2,1],["rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",1,100]]],"rhsgref_helmet_pasgt_3color_desert_rhino","",["rhsusf_bino_m24_ARD","","","",[],[],""],["ItemMap","ItemAndroid","tf_anprc152_26","ItemCompass","ItemWatch","CUP_NVG_PVS14"]];

elp_usmc = [
	["Rifleman", elp_usmc_rifleman],
	["Anti Tank Rifleman", elp_usmc_antitank],
	["Grenadier", epl_usmc_grenadier],
	["Light Machine Gun", epl_usmc_lmg],
	["Medium Machine Gun", epl_usmc_mmg],
	["Team Leader", epl_usmc_teamleader],
	["Element Leader", epl_usmc_elementlead],
	["SARC", epl_usmc_sarc],
	["Marksman", epl_usmc_marksman],
	["Sniper", epl_usmc_sniper],
	["Spotter", epl_usmc_spotter],
	["JTAC", epl_usmc_jtac],
	["Radio Operator", epl_usmc_radiooperator],
	["EOD", epl_usmc_eod],
	["Base Command", elp_usmc_basecommand],
	["Base Command - No Radio", epl_usmc_basecommand_noradio]
];


////Armed Forces of the Russian Federation
elp_afrf_rifleman = [["rhs_weap_ak74m_camo","CUP_muzzle_mfsup_Flashhider_545x39_OD","rhs_acc_perst1ik","rhs_acc_okp7_dovetail",["rhs_30Rnd_545x39_7N10_camo_AK",30],[],""],[],["rhs_weap_makarov_pm","","","",["rhs_mag_9x18_8_57N181S",8],[],""],["rhs_uniform_vdv_emr",[]],["rhs_6b23_digi_6sh92_radio",[["rhs_30Rnd_545x39_7N10_camo_AK",10,30],["rhs_mag_9x18_8_57N181S",2,8]]],["rhs_assault_umbts",[["ACE_fieldDressing",15],["ACE_adenosine",2],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_splint",8],["ACE_tourniquet",4],["ACE_EntrenchingTool",1],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_Flashlight_XL50",1]]],"rhs_6b27m_digi","",["rhs_pdu4","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ACE_Altimeter","rhs_1PN138"]];
elp_afrf_medic =[["rhs_weap_asval_grip","","rhs_acc_perst1ik_ris","rhs_acc_okp7_dovetail",["rhs_20rnd_9x39mm_SP6",20],[],"rhs_acc_grip_ffg2"],[],["rhs_weap_makarov_pm","","","",["rhs_mag_9x18_8_57N181S",8],[],""],["rhs_uniform_vdv_emr",[["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["CUP_8Rnd_9x18_Makarov_M",3,8]]],["rhs_6b23_digi_medic",[["ACE_CableTie",2],["rhs_20rnd_9x39mm_SP6",15,20]]],["rhs_assault_umbts",[["ACE_fieldDressing",50],["ACE_bloodIV_500",8],["ACE_bloodIV_250",11],["ACE_personalAidKit",1],["ACE_morphine",15],["ACE_epinephrine",15],["ACE_adenosine",10],["ACE_splint",15],["ACE_bloodIV",3],["ACE_tourniquet",12]]],"rhs_6b27m_digi","",["rhs_pdu4","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ACE_Altimeter","rhs_1PN138"]];
elp_afrf_machinegunner = [["rhs_weap_pkp","","","rhs_acc_pkas",["150Rnd_762x54_Box",150],[],""],[],["rhs_weap_makarov_pm","","","",["rhs_mag_9x18_8_57N181S",8],[],""],["rhs_uniform_vdv_emr",[]],["rhs_6b23_digi_6sh92_headset",[["rhs_30Rnd_545x39_7N10_camo_AK",10,30],["rhs_mag_9x18_8_57N181S",2,8]]],["rhs_assault_umbts",[["ACE_fieldDressing",15],["ACE_adenosine",2],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_splint",8],["ACE_tourniquet",4],["ACE_EntrenchingTool",1],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_CableTie",2],["150Rnd_762x54_Box",3,150]]],"rhs_6b27m_digi","",["rhs_pdu4","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ACE_Altimeter","rhs_1PN138"]];
elp_afrf_elementleader = [["rhs_weap_ak103_gp25","CUP_muzzle_mfsup_Flashhider_762x39_Black","","rhs_acc_okp7_dovetail",["rhs_30Rnd_762x39mm_polymer",30],[],""],[],["rhs_weap_makarov_pm","","","",["CUP_8Rnd_9x18_Makarov_M",8],[],""],["rhs_uniform_vdv_emr",[["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["CUP_8Rnd_9x18_Makarov_M",4,8]]],["rhs_6b23_digi_6sh92_vog",[["rhs_30Rnd_762x39mm_polymer",8,30]]],["rhs_assault_umbts",[["ACE_fieldDressing",15],["ACE_adenosine",2],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_splint",8],["ACE_tourniquet",4],["ACE_EntrenchingTool",1],["ACE_CableTie",2],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["rhs_30Rnd_762x39mm_polymer",7,30],["rhs_mag_9x18_8_57N181S",3,8]]],"rhs_6b28_green","",["rhs_pdu4","","","",[],[],""],["ItemMap","ItemMicroDAGR","","ItemCompass","ACE_Altimeter","rhs_1PN138"]];
elp_afrf_teamleader = [["rhs_weap_ak74m_fullplum_gp25","CUP_muzzle_mfsup_Flashhider_545x39_Black","","rhs_acc_okp7_dovetail",["rhs_30Rnd_545x39_7N10_plum_AK",30],["rhs_VOG25",1],""],[],["rhs_weap_makarov_pm","","","",["CUP_8Rnd_9x18_Makarov_M",8],[],""],["rhs_uniform_vdv_emr",[["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_EntrenchingTool",1],["ACE_CableTie",1],["CUP_8Rnd_9x18_Makarov_M",4,8]]],["rhs_6b23_digi_6sh92_Vog_Radio_Spetsnaz",[["rhs_30Rnd_545x39_7N10_plum_AK",10,30],["rhs_VOG25",6,1],["rhs_VG40OP_white",1,1]]],["tf_rt1523g_bwmod",[["ACE_fieldDressing",15],["ACE_adenosine",2],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_splint",4]]],"rhs_6b27m_green","",["rhs_pdu4","","","",[],[],""],["ItemMap","ItemMicroDAGR","","ItemCompass","ACE_Altimeter","rhs_1PN138"]];
elp_afrf_teamchief =[["rhs_weap_ak74m_fullplum_gp25","CUP_muzzle_mfsup_Flashhider_545x39_Black","","rhs_acc_okp7_dovetail",["rhs_30Rnd_545x39_7N10_plum_AK",30],["rhs_VOG25",1],""],[],["rhs_weap_makarov_pm","","","",["CUP_8Rnd_9x18_Makarov_M",8],[],""],["rhs_uniform_vdv_emr",[["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_EntrenchingTool",1],["ACE_CableTie",1],["CUP_8Rnd_9x18_Makarov_M",4,8]]],["rhs_6b23_digi_6sh92_Vog_Radio_Spetsnaz",[["rhs_30Rnd_545x39_7N10_plum_AK",10,30],["rhs_VOG25",6,1],["rhs_VG40OP_white",1,1]]],["rhs_assault_umbts",[["ACE_fieldDressing",15],["ACE_adenosine",2],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_splint",4]]],"rhs_6b27m_green","",["rhs_pdu4","","","",[],[],""],["ItemMap","ItemMicroDAGR","","ItemCompass","ACE_Altimeter","rhs_1PN138"]];
elp_afrf_teammedic = [["rhs_weap_asval_grip","","rhs_acc_perst1ik_ris","rhs_acc_okp7_dovetail",["rhs_20rnd_9x39mm_SP6",20],[],"rhs_acc_grip_ffg2"],[],["rhs_weap_makarov_pm","","","",["rhs_mag_9x18_8_57N181S",8],[],""],["rhs_uniform_vdv_emr",[["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["CUP_8Rnd_9x18_Makarov_M",3,8]]],["rhs_6b23_digi_medic",[["ACE_CableTie",2],["rhs_20rnd_9x39mm_SP6",15,20]]],["rhs_assault_umbts",[["ACE_fieldDressing",50],["ACE_bloodIV_500",8],["ACE_bloodIV_250",11],["ACE_personalAidKit",1],["ACE_morphine",15],["ACE_epinephrine",15],["ACE_adenosine",10],["ACE_splint",15],["ACE_bloodIV",3],["ACE_tourniquet",12]]],"rhs_6b27m_green","",["rhs_pdu4","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ACE_Altimeter","rhs_1PN138"]];
elp_afrf_specialist_aa = [["rhs_weap_aks74n","rhs_acc_dtk2","rhs_acc_perst1ik","rhs_acc_okp7_dovetail",["rhs_30Rnd_545x39_7N10_plum_AK",30],[],""],["rhs_weap_igla","","","",["rhs_mag_9k38_rocket",1],[],""],["rhs_weap_makarov_pm","","","",["rhs_mag_9x18_8_57N181S",8],[],""],["rhs_uniform_vdv_emr",[]],["rhs_6b23_digi_6sh92_radio",[["rhs_mag_9x18_8_57N181S",2,8],["rhs_30Rnd_545x39_7N10_plum_AK",10,30]]],["B_Carryall_oli",[["ACE_fieldDressing",10],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_splint",8],["ACE_tourniquet",4],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_Flashlight_XL50",1],["rhs_mag_9k38_rocket",2,1]]],"rhs_6b27m_digi","",["rhs_pdu4","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ACE_Altimeter","rhs_1PN138"]];
elp_afrf_specialist_at_rpg26 = [["rhs_weap_aks74n","rhs_acc_dtk2","rhs_acc_perst1ik","rhs_acc_okp7_dovetail",["rhs_30Rnd_545x39_7N10_plum_AK",30],[],""],["rhs_weap_rpg26","","","",[],[],""],["rhs_weap_makarov_pm","","","",["rhs_mag_9x18_8_57N181S",8],[],""],["rhs_uniform_vdv_emr",[]],["rhs_6b23_digi_6sh92_radio",[["rhs_mag_9x18_8_57N181S",2,8],["rhs_30Rnd_545x39_7N10_plum_AK",10,30]]],["rhs_assault_umbts",[["ACE_fieldDressing",10],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_splint",8],["ACE_tourniquet",4],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_Flashlight_XL50",1]]],"rhs_6b27m_digi","",["rhs_pdu4","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ACE_Altimeter","rhs_1PN138"]];
elp_afrf_specialist_at_rpg7v2 = [["rhs_weap_aks74n","rhs_acc_dtk2","rhs_acc_perst1ik","rhs_acc_okp7_dovetail",["rhs_30Rnd_545x39_7N10_plum_AK",30],[],""],["rhs_weap_rpg7","","","",["rhs_rpg7_PG7VL_mag",1],[],""],["rhs_weap_makarov_pm","","","",["rhs_mag_9x18_8_57N181S",8],[],""],["rhs_uniform_vdv_emr",[]],["rhs_6b23_digi_6sh92_radio",[["rhs_mag_9x18_8_57N181S",2,8],["rhs_30Rnd_545x39_7N10_plum_AK",10,30]]],["B_Carryall_oli",[["ACE_fieldDressing",10],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_splint",8],["ACE_tourniquet",4],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_Flashlight_XL50",1],["rhs_rpg7_PG7VL_mag",7,1]]],"rhs_6b27m_digi","",["rhs_pdu4","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ACE_Altimeter","rhs_1PN138"]];

elp_afrf = [
	["Rifleman", elp_afrf_rifleman],
	["Medic", elp_afrf_medic],
	["Machine Gunner", elp_afrf_machinegunner],
	["Element Leader", elp_afrf_elementleader],
	["Team Leader", elp_afrf_teamleader],
	["Team Chief", elp_afrf_teamchief],
	["Team Medic", elp_afrf_teammedic],
	["Specialist (AA)", elp_afrf_specialist_aa],
	["Specialist (RPG-26)", elp_afrf_specialist_at_rpg26],
	["Specialist (RPG-7v2)", elp_afrf_specialist_at_rpg7v2]
];

//Factions
//FactionListArray = ["Raiders", "PMC"];
elp_factions = [
	["Raiders", elp_raiders], 
	["USMC 2001-2004", elp_usmc],
	["Russian Federation", elp_afrf]
];